Fix bad dry-run flag
The tutorial uses `--dryrun`, which doesn't work:
```
error: unknown option '--dryrun'
(Did you mean --dry-run?)
```

This simply updates to the correct flag.